export const SPORTS = [
  'Arts martiaux',
  'Basketball',
  'Boxe',
  'Course à pied',
  'Cross-training',
  'Crossfit',
  'Cyclisme',
  'Danse',
  'Escalade',
  'Fitness',
  'Football',
  'Golf',
  'HIIT',
  'Méditation',
  'MMA',
  'Musculation',
  'Natation',
  'Pilates',
  'Préparation physique',
  'Rééducation',
  'Rugby',
  'Self-défense',
  'Ski',
  'Stretching',
  'Surf',
  'Tennis',
  'Volleyball',
  'Yoga',
] as const;

export type Sport = (typeof SPORTS)[number];
